export const HOME_PROMPTS = [
  'What was their favorite subject at school?',
  'What do you want to remember about them?',
  'What did they love to cook?',
  'What made them laugh?',
  'Where did they feel most at home?',
  'What is a small habit of theirs you still think about?',
  'What was their childhood home like?',
  'What kind of music did they listen to when nobody was around?',
  'What was their favorite song to sing or hum?',
  'What advice did they give you that actually stuck?',
  'What phrase or saying did they repeat all the time?',
  'How did they take their tea or coffee?',
  'What was a favorite family tradition they started or preserved?',
  'What were they doing when they felt most alive?',
  'What was their very first job?',
  'How did they react when things went completely wrong?',
  'What did their signature dish taste or smell like?',
  'What was a story they loved telling over and over?',
  'What was their favorite room in the house?',
  'What kind of books or stories did they enjoy?',
  'What was a gift they gave you that you still treasure?',
  'How did they celebrate birthdays or special milestones?',
  'What was their morning or bedtime routine?',
  'What pet or animal did they love the most?',
  'How did they express love without using words?',
  'What was a place they always dreamed of visiting?',
  'What was their favorite time of year or season?',
  'What handmade thing did they build, sew, or create?',
  'What was a nickname they had or gave to others?',
  'What was a challenge they overcame that shaped who they were?',
  'What was their favorite treat or sweet snack?',
  'What did their handwriting look like?',
  'What kind of clothes or style made them feel like themselves?',
  'What was a movie or play that moved them deeply?',
  'How did they handle argument or conflict with family?',
  'What was their favorite spot in the garden or outdoors?',
  'What lesson did they learn the hard way?',
  'What made them feel proud of you or someone else?',
  'What was a secret talent or skill few people knew they had?',
  'How did they spend their Sundays or days off?',
  'What was a favorite memory you shared during a car ride or trip?',
  'What was something they were super stubborn about?',
  'How did they greet you when you walked through the door?',
  'What was their favorite holiday meal or dish?',
  'What kind of jokes or sense of humor did they have?',
  'What was a piece of clothing they wore until it fell apart?',
  'How did they show comfort when you were sick or sad?',
  'What was a sport, game, or hobby they were passionate about?',
  'What was their favorite flower or tree?',
  'What did they do right after waking up in the morning?',
  'What was a historical event they lived through and talked about?',
  'How did they meet their partner or spouse?',
  'What was their favorite scent, perfume, or flower aroma?',
  'What was a rule in the house that everyone had to follow?',
  'What was a prank, joke, or funny mishap they were involved in?',
  'What did their workspace or kitchen counter look like?',
  'What was a movie or TV show they never missed?',
  'What was a heirloom or old item they kept in a drawer?',
  'What did they do to relax after a long day?',
  'What was a values or belief they held with deep conviction?',
  'What was a storm, blizzard, or heatwave memory with them?',
  'How did they react when you shared good news with them?',
  'What was their favorite game to play at family gatherings?',
  'What was a letter or card they wrote that you saved?',
  'What was something they bought that brought them sheer joy?',
  'How did they style or care for their hair?',
  'What was a summer memory you have with them?',
  'What was a winter or holiday memory you have with them?',
  'What was a song that instantly reminds you of them?',
  'How did they handle stress or difficult news?',
  'What was their favorite drink on a warm day?',
  'What was a lesson about money or work they taught you?',
  'What was a moment you saw them show rare emotion or tears?',
  'What was their favorite object in their wallet or purse?',
  'What was a place in town they frequented every week?',
  'What was a story about their parents or grandparents they told?',
  'How did they act around babies or young children?',
  'What was a hobby they picked up later in life?',
  'What was a compliment they gave you that meant the world?',
  'What was a favorite dessert they could never pass up?',
  'How did they make people feel welcomed in their home?',
  'What was a photo of them that captures their true spirit?',
  'What was something they always carried in their pocket or bag?',
  'What was a family recipe that only they could get right?',
  'How did they handle getting older or changing health?',
  'What was a project in the yard or house they spent weeks on?',
  'What was a radio show or podcast they loved listening to?',
  'What was a dream they had that they achieved?',
  'What was a time they stood up for someone else?',
  'What was a favorite smell in their house or kitchen?',
  'What was a silly habit that used to make everyone smile?',
  'How did they sign off on notes or text messages?',
  'What was their favorite place to watch the sunset or sunrise?',
  'What was a skill they taught you step by step?',
  'What was something they refused to throw away?',
  'How did they react when you surprised them?',
  'What was a trip or vacation story they loved reliving?',
  'What was a favorite tradition from their own childhood?',
  'What was a moment of quiet peace you shared together?',
  'What is a legacy or value of theirs you hope to pass on?',
  'What would they say if they were sitting next to you right now?',
  'What was their favorite comfort food when they needed a lift?',
  'What was a funny misunderstanding or mispronunciation they used?',
  'What is the single best memory you have with them?',
]

export const RELATIONSHIP_SUGGESTIONS = [
  'grandmother',
  'grandfather',
  'great-grandmother',
  'great-grandfather',
  'mother',
  'father',
  'parent',
  'aunt',
  'uncle',
  'cousin',
  'sister',
  'brother',
  'daughter',
  'son',
  'grandchild',
  'chosen family',
  'friend',
  'neighbor',
  'teacher',
  'mentor',
]
